# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

AdminUser.create([
  { :email => "admin@example.com", :encrypted_password => "$2a$10$2xHGOIW4mMg5qFYF47kvju5YP2fcacFpLMV5/ftZ96ROnbVAZKRoa", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 1, :current_sign_in_at => "2013-03-24 21:46:29", :last_sign_in_at => "2013-03-24 21:46:29", :current_sign_in_ip => "127.0.0.1", :last_sign_in_ip => "127.0.0.1", :created_at => "2013-03-24 21:42:49", :updated_at => "2013-03-24 21:46:29" }
], :without_protection => true )



Course.create([
  { :name => "Website Basics", :url => "http://teamtreehouse.com/library/websites/website-basics", :estimated_time => 1.5, :subject_id => 1, :created_at => nil, :updated_at => "2013-03-22 17:29:53", :treehouse_badges => 1, :course_provider_id => 2, :days_due_before_class => 28 },
  { :name => "Technology Foundations", :url => "http://teamtreehouse.com/library/websites/technology-foundations", :estimated_time => 2.0, :subject_id => 1, :created_at => nil, :updated_at => "2013-03-22 17:29:53", :treehouse_badges => 1, :course_provider_id => 2, :days_due_before_class => 28 },
  { :name => "Aesthetic Foundations", :url => "http://teamtreehouse.com/library/websites/aesthetic-foundations", :estimated_time => 2.5, :subject_id => 1, :created_at => nil, :updated_at => "2013-03-22 14:56:04", :treehouse_badges => 3, :course_provider_id => 2, :days_due_before_class => 28 },
  { :name => "Learn the Command Line the Hard Way", :url => "http://cli.learncodethehardway.org/book/", :estimated_time => 3.0, :subject_id => 3, :created_at => nil, :updated_at => nil, :treehouse_badges => nil, :course_provider_id => 0, :days_due_before_class => 28 },
  { :name => "Command Line Basics", :url => "http://blog.teamtreehouse.com/command-line-basics", :estimated_time => 0.5, :subject_id => 3, :created_at => nil, :updated_at => nil, :treehouse_badges => nil, :course_provider_id => 2, :days_due_before_class => 28 },
  { :name => "Bash Basics", :url => "https://gist.github.com/a8a7ca963e37e0b108b9", :estimated_time => 0.5, :subject_id => 3, :created_at => nil, :updated_at => nil, :treehouse_badges => nil, :course_provider_id => 0, :days_due_before_class => 28 },
  { :name => "Learn SQL the Hardway", :url => "http://sql.learncodethehardway.org/book/", :estimated_time => 4.0, :subject_id => 4, :created_at => nil, :updated_at => nil, :treehouse_badges => nil, :course_provider_id => 0, :days_due_before_class => 28 },
  { :name => "Google's MySQL Tutorial", :url => "http://code.google.com/edu/tools101/mysql.html", :estimated_time => 2.0, :subject_id => 4, :created_at => nil, :updated_at => nil, :treehouse_badges => nil, :course_provider_id => 0, :days_due_before_class => 28 },
  { :name => "HTML & CSS Tutorial", :url => "http://learn.shayhowe.com/html-css/", :estimated_time => 2.0, :subject_id => 5, :created_at => nil, :updated_at => nil, :treehouse_badges => nil, :course_provider_id => 0, :days_due_before_class => 28 },
  { :name => "HTML", :url => "http://teamtreehouse.com/library/websites/html", :estimated_time => 6.0, :subject_id => 5, :created_at => nil, :updated_at => "2013-03-22 14:56:08", :treehouse_badges => 7, :course_provider_id => 2, :days_due_before_class => 28 },
  { :name => "Functional HTML5 & CSS3", :url => "http://www.codeschool.com/courses/functional-html5-css3", :estimated_time => 6.0, :subject_id => 5, :created_at => nil, :updated_at => nil, :treehouse_badges => nil, :course_provider_id => 1, :days_due_before_class => 28 },
  { :name => "CSS Foundations", :url => "http://teamtreehouse.com/library/websites/css-foundations", :estimated_time => 6.0, :subject_id => 6, :created_at => nil, :updated_at => "2013-03-22 14:56:09", :treehouse_badges => 8, :course_provider_id => 2, :days_due_before_class => 28 },
  { :name => "CSS3", :url => "http://teamtreehouse.com/library/websites/css3", :estimated_time => 4.0, :subject_id => 6, :created_at => nil, :updated_at => "2013-03-22 19:25:56", :treehouse_badges => 11, :course_provider_id => 2, :days_due_before_class => 21 },
  { :name => "Build a Responsive Website", :url => "http://teamtreehouse.com/library/websites/build-a-responsive-website/", :estimated_time => 4.0, :subject_id => 6, :created_at => nil, :updated_at => "2013-03-22 14:56:10", :treehouse_badges => 5, :course_provider_id => 2, :days_due_before_class => 21 },
  { :name => "Try Git", :url => "http://www.codeschool.com/courses/try-git", :estimated_time => 1.0, :subject_id => 7, :created_at => nil, :updated_at => nil, :treehouse_badges => nil, :course_provider_id => 1, :days_due_before_class => 21 },
  { :name => "Git Real", :url => "http://www.codeschool.com/courses/git-real", :estimated_time => 4.0, :subject_id => 7, :created_at => nil, :updated_at => nil, :treehouse_badges => nil, :course_provider_id => 1, :days_due_before_class => 21 },
  { :name => "Git Immersion", :url => "http://gitimmersion.com/", :estimated_time => 3.0, :subject_id => 7, :created_at => nil, :updated_at => nil, :treehouse_badges => nil, :course_provider_id => 0, :days_due_before_class => 21 },
  { :name => "The Git Book", :url => "http://git-scm.com/book", :estimated_time => 6.0, :subject_id => 7, :created_at => nil, :updated_at => nil, :treehouse_badges => nil, :course_provider_id => 0, :days_due_before_class => 21 },
  { :name => "Git Videos", :url => "http://git-scm.com/videos", :estimated_time => 1.0, :subject_id => 7, :created_at => nil, :updated_at => nil, :treehouse_badges => nil, :course_provider_id => 0, :days_due_before_class => 21 },
  { :name => "Try Ruby", :url => "http://www.codeschool.com/courses/try-ruby", :estimated_time => 1.0, :subject_id => 10, :created_at => nil, :updated_at => nil, :treehouse_badges => nil, :course_provider_id => 1, :days_due_before_class => 21 },
  { :name => "JavaScript Foundations", :url => "http://teamtreehouse.com/library/websites/javascript-foundations", :estimated_time => 6.0, :subject_id => 9, :created_at => nil, :updated_at => "2013-03-22 14:56:11", :treehouse_badges => 6, :course_provider_id => 2, :days_due_before_class => 21 },
  { :name => "jQuery Air: First Flight", :url => "http://www.codeschool.com/courses/jquery-air-first-flight", :estimated_time => 6.0, :subject_id => 9, :created_at => nil, :updated_at => nil, :treehouse_badges => nil, :course_provider_id => 1, :days_due_before_class => 21 },
  { :name => "jQuery Air: Captain's Log", :url => "http://www.codeschool.com/courses/jquery-air-captains-log", :estimated_time => 6.0, :subject_id => 9, :created_at => nil, :updated_at => nil, :treehouse_badges => nil, :course_provider_id => 1, :days_due_before_class => 14 },
  { :name => "Learn to Program", :url => "http://pine.fm/LearnToProgram/", :estimated_time => 10.0, :subject_id => 10, :created_at => nil, :updated_at => nil, :treehouse_badges => nil, :course_provider_id => 0, :days_due_before_class => 14 },
  { :name => "Ruby Foundations", :url => "http://teamtreehouse.com/library/programming-2/ruby-foundations", :estimated_time => 10.0, :subject_id => 10, :created_at => nil, :updated_at => "2013-03-22 14:56:14", :treehouse_badges => 14, :course_provider_id => 2, :days_due_before_class => 14 },
  { :name => "Ruby Bits", :url => "http://www.codeschool.com/courses/ruby-bits", :estimated_time => 6.0, :subject_id => 10, :created_at => nil, :updated_at => nil, :treehouse_badges => nil, :course_provider_id => 1, :days_due_before_class => 14 },
  { :name => "Getting Started with Rails Guide", :url => "http://guides.rubyonrails.org/getting_started.html", :estimated_time => 2.0, :subject_id => 11, :created_at => nil, :updated_at => nil, :treehouse_badges => nil, :course_provider_id => 0, :days_due_before_class => 14 },
  { :name => "Rails for Zombies Redux", :url => "http://www.codeschool.com/courses/rails-for-zombies-redux", :estimated_time => 4.0, :subject_id => 11, :created_at => nil, :updated_at => nil, :treehouse_badges => nil, :course_provider_id => 1, :days_due_before_class => 7 },
  { :name => "Rails for Zombies 2", :url => "http://www.codeschool.com/courses/rails-for-zombies-2", :estimated_time => 4.0, :subject_id => 11, :created_at => nil, :updated_at => nil, :treehouse_badges => nil, :course_provider_id => 1, :days_due_before_class => 7 },
  { :name => "Build a Simple Ruby on Rails Application", :url => "http://teamtreehouse.com/library/programming-2/build-a-simple-version-of-facebook", :estimated_time => 12.0, :subject_id => 11, :created_at => nil, :updated_at => "2013-03-22 14:56:15", :treehouse_badges => 9, :course_provider_id => 2, :days_due_before_class => 7 },
  { :name => "Testing with RSpec", :url => "http://www.codeschool.com/courses/testing-with-rspec", :estimated_time => 0.0, :subject_id => 12, :created_at => nil, :updated_at => nil, :treehouse_badges => nil, :course_provider_id => 1, :days_due_before_class => 7 },
  { :name => "Rails Testing for Zombies", :url => "http://www.codeschool.com/courses/rails-testing-for-zombies", :estimated_time => 0.0, :subject_id => 12, :created_at => nil, :updated_at => nil, :treehouse_badges => nil, :course_provider_id => 1, :days_due_before_class => 7 },
  { :name => "Rails Best Practices", :url => "http://www.codeschool.com/courses/rails-best-practices", :estimated_time => 0.0, :subject_id => 13, :created_at => nil, :updated_at => nil, :treehouse_badges => nil, :course_provider_id => 1, :days_due_before_class => 7 }
], :without_protection => true )



CourseProvider.create([
  { :name => "code school", :created_at => 1, :updated_at => 1 },
  { :name => "treehouse", :created_at => 1, :updated_at => 1 }
], :without_protection => true )



Event.create([
  { :name => "NYC on Rails", :start_at => "2013-03-28 19:00:00", :end_at => "2013-03-28 21:00:00", :created_at => "2013-03-26 18:04:56", :updated_at => "2013-03-26 18:04:56", :location => nil, :address => nil }
], :without_protection => true )



Semester.create([
  { :start => nil, :end => nil, :name => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



Subject.create([
  { :name => "The Web", :created_at => "2013-03-20 00:29:03", :updated_at => "2013-03-20 00:29:03" },
  { :name => "Term Definitions", :created_at => "2013-03-20 00:29:03", :updated_at => "2013-03-20 00:29:03" },
  { :name => "The Command Line", :created_at => "2013-03-20 00:29:03", :updated_at => "2013-03-20 00:29:03" },
  { :name => "SQL & Databases", :created_at => "2013-03-20 00:29:03", :updated_at => "2013-03-20 00:29:03" },
  { :name => "Hypertext Markup Language", :created_at => "2013-03-20 00:29:03", :updated_at => "2013-03-20 00:29:03" },
  { :name => "Cascading Style Sheets", :created_at => "2013-03-20 00:29:03", :updated_at => "2013-03-20 00:29:03" },
  { :name => "Git: Version Control", :created_at => "2013-03-20 00:29:03", :updated_at => "2013-03-20 00:29:03" },
  { :name => "Basics", :created_at => 1, :updated_at => 1 },
  { :name => "Javascript", :created_at => 1, :updated_at => 1 },
  { :name => "Ruby", :created_at => 1, :updated_at => 1 },
  { :name => "Rails", :created_at => 1, :updated_at => 1 },
  { :name => "Testing", :created_at => 1, :updated_at => 1 },
  { :name => "Best Practices", :created_at => 1, :updated_at => 1 }
], :without_protection => true )



User.create([
  { :email => "masha.rikhter@gmail.com", :codeschool_login => "mrikhter", :treehouse_login => "masharikhter", :created_at => 1, :updated_at => 1, :phone_number => "4049661321", :first_name => "masha", :last_name => "rikhter", :password_digest => nil },
  { :email => "hunternz@gmail.com", :codeschool_login => "aviflombaum", :treehouse_login => "aviflombaum", :created_at => 1, :updated_at => 1, :phone_number => "1", :first_name => "Tim", :last_name => "Hunter", :password_digest => nil },
  { :email => "email.erin@gmail.com", :codeschool_login => "aviflombaum", :treehouse_login => "aviflombaum", :created_at => "2013-03-22 19:07:09", :updated_at => "2013-03-22 19:07:09", :phone_number => "555-555-5555", :first_name => "Erin", :last_name => "Lee", :password_digest => "$2a$10$vdJ0es9zAycxEthX.cwkReMx43I7XYogHNJMx5VP4nL2IK/Zqfo2O" },
  { :email => "daniel.gantz@gmail.com", :codeschool_login => "mrikhter", :treehouse_login => "masharikhter", :created_at => "2013-03-22 19:16:20", :updated_at => "2013-03-22 19:16:20", :phone_number => "404-966-1321", :first_name => "Daniel", :last_name => "Gantz", :password_digest => "$2a$10$2B.PV.AAtC95XlwZmKuZwOIfgUnULfZ/zq2tErSuAn1W9J2c0Ja3K" }
], :without_protection => true )



UserCourse.create([
  { :course_id => 58, :user_id => 1, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-21 21:11:32", :updated_at => "2013-03-22 17:30:02", :treehouse_badges_completed => 1 },
  { :course_id => 59, :user_id => 1, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-21 21:11:32", :updated_at => "2013-03-22 17:55:40", :treehouse_badges_completed => 1 },
  { :course_id => 60, :user_id => 1, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-21 21:11:32", :updated_at => "2013-03-22 14:57:43", :treehouse_badges_completed => 3 },
  { :course_id => 61, :user_id => 1, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-21 21:11:32", :updated_at => "2013-03-21 21:11:32", :treehouse_badges_completed => nil },
  { :course_id => 62, :user_id => 1, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-21 21:11:32", :updated_at => "2013-03-21 21:11:32", :treehouse_badges_completed => nil },
  { :course_id => 63, :user_id => 1, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-21 21:11:32", :updated_at => "2013-03-21 21:11:32", :treehouse_badges_completed => nil },
  { :course_id => 64, :user_id => 1, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-21 21:11:32", :updated_at => "2013-03-21 21:11:32", :treehouse_badges_completed => nil },
  { :course_id => 65, :user_id => 1, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-21 21:11:32", :updated_at => "2013-03-21 21:11:32", :treehouse_badges_completed => nil },
  { :course_id => 66, :user_id => 1, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-21 21:11:32", :updated_at => "2013-03-21 21:11:32", :treehouse_badges_completed => nil },
  { :course_id => 67, :user_id => 1, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-21 21:11:32", :updated_at => "2013-03-22 17:47:19", :treehouse_badges_completed => 7 },
  { :course_id => 68, :user_id => 1, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-21 21:11:32", :updated_at => "2013-03-21 21:11:37", :treehouse_badges_completed => nil },
  { :course_id => 69, :user_id => 1, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-21 21:11:32", :updated_at => "2013-03-22 14:57:43", :treehouse_badges_completed => 8 },
  { :course_id => 70, :user_id => 1, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-21 21:11:32", :updated_at => "2013-03-21 21:11:37", :treehouse_badges_completed => nil },
  { :course_id => 71, :user_id => 1, :progress => 80, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-21 21:11:32", :updated_at => "2013-03-22 17:52:21", :treehouse_badges_completed => 4 },
  { :course_id => 72, :user_id => 1, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-21 21:11:32", :updated_at => "2013-03-21 21:11:37", :treehouse_badges_completed => nil },
  { :course_id => 73, :user_id => 1, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-21 21:11:32", :updated_at => "2013-03-21 21:11:37", :treehouse_badges_completed => nil },
  { :course_id => 74, :user_id => 1, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-21 21:11:32", :updated_at => "2013-03-21 21:11:32", :treehouse_badges_completed => nil },
  { :course_id => 75, :user_id => 1, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-21 21:11:32", :updated_at => "2013-03-21 21:11:32", :treehouse_badges_completed => nil },
  { :course_id => 76, :user_id => 1, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-21 21:11:32", :updated_at => "2013-03-21 21:11:32", :treehouse_badges_completed => nil },
  { :course_id => 77, :user_id => 1, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-21 21:11:32", :updated_at => "2013-03-21 21:11:37", :treehouse_badges_completed => nil },
  { :course_id => 79, :user_id => 1, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-21 21:11:32", :updated_at => "2013-03-22 17:53:32", :treehouse_badges_completed => 6 },
  { :course_id => 80, :user_id => 1, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-21 21:11:32", :updated_at => "2013-03-21 21:11:37", :treehouse_badges_completed => nil },
  { :course_id => 81, :user_id => 1, :progress => 19, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-21 21:11:32", :updated_at => "2013-03-21 21:11:37", :treehouse_badges_completed => nil },
  { :course_id => 82, :user_id => 1, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-21 21:11:32", :updated_at => "2013-03-21 21:11:32", :treehouse_badges_completed => nil },
  { :course_id => 83, :user_id => 1, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-21 21:11:32", :updated_at => "2013-03-22 14:57:43", :treehouse_badges_completed => 14 },
  { :course_id => 84, :user_id => 1, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-21 21:11:32", :updated_at => "2013-03-21 21:11:37", :treehouse_badges_completed => nil },
  { :course_id => 85, :user_id => 1, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-21 21:11:32", :updated_at => "2013-03-21 21:11:32", :treehouse_badges_completed => nil },
  { :course_id => 86, :user_id => 1, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-21 21:11:32", :updated_at => "2013-03-21 21:11:37", :treehouse_badges_completed => nil },
  { :course_id => 87, :user_id => 1, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-21 21:11:32", :updated_at => "2013-03-21 21:11:37", :treehouse_badges_completed => nil },
  { :course_id => 88, :user_id => 1, :progress => 66, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-21 21:11:32", :updated_at => "2013-03-22 17:52:21", :treehouse_badges_completed => 6 },
  { :course_id => 89, :user_id => 1, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-21 21:11:32", :updated_at => "2013-03-21 21:11:32", :treehouse_badges_completed => nil },
  { :course_id => 90, :user_id => 1, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-21 21:11:33", :updated_at => "2013-03-21 21:11:33", :treehouse_badges_completed => nil },
  { :course_id => 91, :user_id => 1, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-21 21:11:33", :updated_at => "2013-03-21 21:11:33", :treehouse_badges_completed => nil },
  { :course_id => 58, :user_id => nil, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:06:30", :updated_at => "2013-03-22 19:06:36", :treehouse_badges_completed => 1 },
  { :course_id => 59, :user_id => nil, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:06:30", :updated_at => "2013-03-22 19:06:36", :treehouse_badges_completed => 1 },
  { :course_id => 60, :user_id => nil, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:06:30", :updated_at => "2013-03-22 19:06:30", :treehouse_badges_completed => 0 },
  { :course_id => 61, :user_id => nil, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:06:30", :updated_at => "2013-03-22 19:06:30", :treehouse_badges_completed => 0 },
  { :course_id => 62, :user_id => nil, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:06:30", :updated_at => "2013-03-22 19:06:30", :treehouse_badges_completed => 0 },
  { :course_id => 63, :user_id => nil, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:06:30", :updated_at => "2013-03-22 19:06:30", :treehouse_badges_completed => 0 },
  { :course_id => 64, :user_id => nil, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:06:30", :updated_at => "2013-03-22 19:06:30", :treehouse_badges_completed => 0 },
  { :course_id => 65, :user_id => nil, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:06:30", :updated_at => "2013-03-22 19:06:30", :treehouse_badges_completed => 0 },
  { :course_id => 66, :user_id => nil, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:06:30", :updated_at => "2013-03-22 19:06:30", :treehouse_badges_completed => 0 },
  { :course_id => 67, :user_id => nil, :progress => 14, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:06:30", :updated_at => "2013-03-22 19:06:36", :treehouse_badges_completed => 1 },
  { :course_id => 68, :user_id => nil, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:06:30", :updated_at => "2013-03-22 19:06:33", :treehouse_badges_completed => 0 },
  { :course_id => 69, :user_id => nil, :progress => 25, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:06:30", :updated_at => "2013-03-22 19:06:36", :treehouse_badges_completed => 2 },
  { :course_id => 70, :user_id => nil, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:06:30", :updated_at => "2013-03-22 19:06:30", :treehouse_badges_completed => 0 },
  { :course_id => 71, :user_id => nil, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:06:30", :updated_at => "2013-03-22 19:06:30", :treehouse_badges_completed => 0 },
  { :course_id => 72, :user_id => nil, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:06:30", :updated_at => "2013-03-22 19:06:33", :treehouse_badges_completed => 0 },
  { :course_id => 73, :user_id => nil, :progress => 33, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:06:30", :updated_at => "2013-03-22 19:06:33", :treehouse_badges_completed => 0 },
  { :course_id => 74, :user_id => nil, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:06:30", :updated_at => "2013-03-22 19:06:30", :treehouse_badges_completed => 0 },
  { :course_id => 75, :user_id => nil, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:06:30", :updated_at => "2013-03-22 19:06:30", :treehouse_badges_completed => 0 },
  { :course_id => 76, :user_id => nil, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:06:30", :updated_at => "2013-03-22 19:06:30", :treehouse_badges_completed => 0 },
  { :course_id => 77, :user_id => nil, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:06:30", :updated_at => "2013-03-22 19:06:33", :treehouse_badges_completed => 0 },
  { :course_id => 79, :user_id => nil, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:06:30", :updated_at => "2013-03-22 19:06:30", :treehouse_badges_completed => 0 },
  { :course_id => 80, :user_id => nil, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:06:30", :updated_at => "2013-03-22 19:06:30", :treehouse_badges_completed => 0 },
  { :course_id => 81, :user_id => nil, :progress => 5, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:06:30", :updated_at => "2013-03-22 19:06:33", :treehouse_badges_completed => 0 },
  { :course_id => 82, :user_id => nil, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:06:30", :updated_at => "2013-03-22 19:06:30", :treehouse_badges_completed => 0 },
  { :course_id => 83, :user_id => nil, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:06:30", :updated_at => "2013-03-22 19:06:30", :treehouse_badges_completed => 0 },
  { :course_id => 84, :user_id => nil, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:06:30", :updated_at => "2013-03-22 19:06:33", :treehouse_badges_completed => 0 },
  { :course_id => 85, :user_id => nil, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:06:30", :updated_at => "2013-03-22 19:06:30", :treehouse_badges_completed => 0 },
  { :course_id => 86, :user_id => nil, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:06:30", :updated_at => "2013-03-22 19:06:33", :treehouse_badges_completed => 0 },
  { :course_id => 87, :user_id => nil, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:06:31", :updated_at => "2013-03-22 19:06:33", :treehouse_badges_completed => 0 },
  { :course_id => 88, :user_id => nil, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:06:31", :updated_at => "2013-03-22 19:06:31", :treehouse_badges_completed => 0 },
  { :course_id => 89, :user_id => nil, :progress => 16, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:06:31", :updated_at => "2013-03-22 19:06:33", :treehouse_badges_completed => 0 },
  { :course_id => 90, :user_id => nil, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:06:31", :updated_at => "2013-03-22 19:06:31", :treehouse_badges_completed => 0 },
  { :course_id => 91, :user_id => nil, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:06:31", :updated_at => "2013-03-22 19:06:33", :treehouse_badges_completed => 0 },
  { :course_id => 58, :user_id => 11, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:07:09", :updated_at => "2013-03-22 19:07:12", :treehouse_badges_completed => 1 },
  { :course_id => 59, :user_id => 11, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:07:09", :updated_at => "2013-03-22 19:07:12", :treehouse_badges_completed => 1 },
  { :course_id => 60, :user_id => 11, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:07:09", :updated_at => "2013-03-22 19:07:09", :treehouse_badges_completed => 0 },
  { :course_id => 61, :user_id => 11, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:07:09", :updated_at => "2013-03-22 19:07:09", :treehouse_badges_completed => 0 },
  { :course_id => 62, :user_id => 11, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:07:09", :updated_at => "2013-03-22 19:07:09", :treehouse_badges_completed => 0 },
  { :course_id => 63, :user_id => 11, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:07:09", :updated_at => "2013-03-22 19:07:09", :treehouse_badges_completed => 0 },
  { :course_id => 64, :user_id => 11, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:07:09", :updated_at => "2013-03-22 19:07:09", :treehouse_badges_completed => 0 },
  { :course_id => 65, :user_id => 11, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:07:09", :updated_at => "2013-03-22 19:07:09", :treehouse_badges_completed => 0 },
  { :course_id => 66, :user_id => 11, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:07:09", :updated_at => "2013-03-22 19:07:09", :treehouse_badges_completed => 0 },
  { :course_id => 67, :user_id => 11, :progress => 14, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:07:09", :updated_at => "2013-03-22 19:07:12", :treehouse_badges_completed => 1 },
  { :course_id => 68, :user_id => 11, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:07:09", :updated_at => "2013-03-22 19:07:10", :treehouse_badges_completed => 0 },
  { :course_id => 69, :user_id => 11, :progress => 25, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:07:09", :updated_at => "2013-03-22 19:07:12", :treehouse_badges_completed => 2 },
  { :course_id => 70, :user_id => 11, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:07:09", :updated_at => "2013-03-22 19:07:09", :treehouse_badges_completed => 0 },
  { :course_id => 71, :user_id => 11, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:07:09", :updated_at => "2013-03-22 19:07:09", :treehouse_badges_completed => 0 },
  { :course_id => 72, :user_id => 11, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:07:09", :updated_at => "2013-03-22 19:07:10", :treehouse_badges_completed => 0 },
  { :course_id => 73, :user_id => 11, :progress => 33, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:07:09", :updated_at => "2013-03-22 19:07:10", :treehouse_badges_completed => 0 },
  { :course_id => 74, :user_id => 11, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:07:09", :updated_at => "2013-03-22 19:07:09", :treehouse_badges_completed => 0 },
  { :course_id => 75, :user_id => 11, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:07:09", :updated_at => "2013-03-22 19:07:09", :treehouse_badges_completed => 0 },
  { :course_id => 76, :user_id => 11, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:07:09", :updated_at => "2013-03-22 19:07:09", :treehouse_badges_completed => 0 },
  { :course_id => 77, :user_id => 11, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:07:09", :updated_at => "2013-03-22 19:07:10", :treehouse_badges_completed => 0 },
  { :course_id => 79, :user_id => 11, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:07:09", :updated_at => "2013-03-22 19:07:09", :treehouse_badges_completed => 0 },
  { :course_id => 80, :user_id => 11, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:07:09", :updated_at => "2013-03-22 19:07:09", :treehouse_badges_completed => 0 },
  { :course_id => 81, :user_id => 11, :progress => 5, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:07:09", :updated_at => "2013-03-22 19:07:10", :treehouse_badges_completed => 0 },
  { :course_id => 82, :user_id => 11, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:07:09", :updated_at => "2013-03-22 19:07:09", :treehouse_badges_completed => 0 },
  { :course_id => 83, :user_id => 11, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:07:09", :updated_at => "2013-03-22 19:07:09", :treehouse_badges_completed => 0 },
  { :course_id => 84, :user_id => 11, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:07:09", :updated_at => "2013-03-22 19:07:10", :treehouse_badges_completed => 0 },
  { :course_id => 85, :user_id => 11, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:07:09", :updated_at => "2013-03-22 19:07:09", :treehouse_badges_completed => 0 },
  { :course_id => 86, :user_id => 11, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:07:09", :updated_at => "2013-03-22 19:07:10", :treehouse_badges_completed => 0 },
  { :course_id => 87, :user_id => 11, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:07:09", :updated_at => "2013-03-22 19:07:10", :treehouse_badges_completed => 0 },
  { :course_id => 88, :user_id => 11, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:07:09", :updated_at => "2013-03-22 19:07:09", :treehouse_badges_completed => 0 },
  { :course_id => 89, :user_id => 11, :progress => 16, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:07:09", :updated_at => "2013-03-22 19:07:10", :treehouse_badges_completed => 0 },
  { :course_id => 90, :user_id => 11, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:07:09", :updated_at => "2013-03-22 19:07:09", :treehouse_badges_completed => 0 },
  { :course_id => 91, :user_id => 11, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:07:09", :updated_at => "2013-03-22 19:07:10", :treehouse_badges_completed => 0 },
  { :course_id => 58, :user_id => 12, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:16:20", :updated_at => "2013-03-22 19:16:37", :treehouse_badges_completed => 1 },
  { :course_id => 59, :user_id => 12, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:16:20", :updated_at => "2013-03-22 19:16:37", :treehouse_badges_completed => 1 },
  { :course_id => 60, :user_id => 12, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:16:20", :updated_at => "2013-03-22 19:16:37", :treehouse_badges_completed => 3 },
  { :course_id => 61, :user_id => 12, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:16:20", :updated_at => "2013-03-22 19:16:20", :treehouse_badges_completed => 0 },
  { :course_id => 62, :user_id => 12, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:16:20", :updated_at => "2013-03-22 19:16:20", :treehouse_badges_completed => 0 },
  { :course_id => 63, :user_id => 12, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:16:20", :updated_at => "2013-03-22 19:16:20", :treehouse_badges_completed => 0 },
  { :course_id => 64, :user_id => 12, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:16:20", :updated_at => "2013-03-22 19:16:20", :treehouse_badges_completed => 0 },
  { :course_id => 65, :user_id => 12, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:16:20", :updated_at => "2013-03-22 19:16:20", :treehouse_badges_completed => 0 },
  { :course_id => 66, :user_id => 12, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:16:20", :updated_at => "2013-03-22 19:16:20", :treehouse_badges_completed => 0 },
  { :course_id => 67, :user_id => 12, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:16:20", :updated_at => "2013-03-22 19:16:37", :treehouse_badges_completed => 7 },
  { :course_id => 68, :user_id => 12, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:16:21", :updated_at => "2013-03-22 19:16:22", :treehouse_badges_completed => 0 },
  { :course_id => 69, :user_id => 12, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:16:21", :updated_at => "2013-03-22 19:16:37", :treehouse_badges_completed => 8 },
  { :course_id => 70, :user_id => 12, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:16:21", :updated_at => "2013-03-22 19:26:02", :treehouse_badges_completed => 11 },
  { :course_id => 71, :user_id => 12, :progress => 80, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:16:21", :updated_at => "2013-03-22 19:16:37", :treehouse_badges_completed => 4 },
  { :course_id => 72, :user_id => 12, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:16:21", :updated_at => "2013-03-22 19:16:22", :treehouse_badges_completed => 0 },
  { :course_id => 73, :user_id => 12, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:16:21", :updated_at => "2013-03-22 19:16:22", :treehouse_badges_completed => 0 },
  { :course_id => 74, :user_id => 12, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:16:21", :updated_at => "2013-03-22 19:16:21", :treehouse_badges_completed => 0 },
  { :course_id => 75, :user_id => 12, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:16:21", :updated_at => "2013-03-22 19:16:21", :treehouse_badges_completed => 0 },
  { :course_id => 76, :user_id => 12, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:16:21", :updated_at => "2013-03-22 19:16:21", :treehouse_badges_completed => 0 },
  { :course_id => 77, :user_id => 12, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:16:21", :updated_at => "2013-03-22 19:16:22", :treehouse_badges_completed => 0 },
  { :course_id => 79, :user_id => 12, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:16:21", :updated_at => "2013-03-22 19:16:37", :treehouse_badges_completed => 6 },
  { :course_id => 80, :user_id => 12, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:16:21", :updated_at => "2013-03-22 19:16:22", :treehouse_badges_completed => 0 },
  { :course_id => 81, :user_id => 12, :progress => 19, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:16:21", :updated_at => "2013-03-22 19:16:22", :treehouse_badges_completed => 0 },
  { :course_id => 82, :user_id => 12, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:16:21", :updated_at => "2013-03-22 19:16:21", :treehouse_badges_completed => 0 },
  { :course_id => 83, :user_id => 12, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:16:21", :updated_at => "2013-03-22 19:16:37", :treehouse_badges_completed => 14 },
  { :course_id => 84, :user_id => 12, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:16:21", :updated_at => "2013-03-22 19:16:22", :treehouse_badges_completed => 0 },
  { :course_id => 85, :user_id => 12, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:16:21", :updated_at => "2013-03-22 19:16:21", :treehouse_badges_completed => 0 },
  { :course_id => 86, :user_id => 12, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:16:21", :updated_at => "2013-03-22 19:16:22", :treehouse_badges_completed => 0 },
  { :course_id => 87, :user_id => 12, :progress => 100, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:16:21", :updated_at => "2013-03-22 19:16:22", :treehouse_badges_completed => 0 },
  { :course_id => 88, :user_id => 12, :progress => 66, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:16:21", :updated_at => "2013-03-22 19:16:37", :treehouse_badges_completed => 6 },
  { :course_id => 89, :user_id => 12, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:16:21", :updated_at => "2013-03-22 19:16:21", :treehouse_badges_completed => 0 },
  { :course_id => 90, :user_id => 12, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:16:21", :updated_at => "2013-03-22 19:16:21", :treehouse_badges_completed => 0 },
  { :course_id => 91, :user_id => 12, :progress => 0, :bookmark => nil, :time_spent => nil, :created_at => "2013-03-22 19:16:21", :updated_at => "2013-03-22 19:16:21", :treehouse_badges_completed => 0 }
], :without_protection => true )


